### ISSUE TITLE
minimal function can work on Windows 10

### ISSUE THREAD

**Issue by 9to1url** [theWebalyst/logtail-dash#5]
Is that possible to just do this function:

* tail a log file and return line by line String.

I used LogWatcher, but only work on Mac and Linux, but I need the Windows to work, using like this:
```rust
let mut log_watcher = LogWatcher::register("C:\\var\log\\check.log".to_string()).unwrap();

log_watcher.watch(&mut move |line: String| {
    println!("Line {}", line);
    LogWatcherAction::None
});
```

Thank you very much.

**Comment by happybeing** [comment]
Yes, logtail uses `linemux` which works on Windows. Closing this, but feel free to reopen.
